### ISSUE TITLE
Comment here to be added as a collaborator

### ISSUE THREAD

**Issue by brianamarie** [githubschool/nov-13#1]
### Comment below - you can say anything 
 We will all be using this repository today. Even though it's public right now, you will not be able to make changes until you're given the correct permissions. We've automated this process via the GitHub API and some fancy chatops. Once you comment, we will add you as a collaborator. 

  You'll also start to receive a lot of emails. (:exclamation:) You can slow these down immediately by clicking the 'unsubscribe' button.

**Comment by jawaharib** [comment]
Hello

**Comment by sujaykondanekar** [comment]
Hi, please add me as a collaborator to this repository.

**Comment by tej1599** [comment]
Please add me as a collaborator

**Comment by iyussuf** [comment]
Hello all

**Comment by jaishaunik** [comment]
Hi

**Comment by bhatchetan** [comment]
Add me as a Collaborator

**Comment by gharish86** [comment]
Hello

**Comment by arvindsbabu** [comment]
Comment

**Comment by ghanashyams** [comment]
Just a test comment

**Comment by Racersclub** [comment]
Hi

**Comment by 17akshat** [comment]
Hi, Please add

**Comment by tom310878** [comment]
This training will be a way to learn more in-depth github features.

**Comment by vinaymbharadwaj** [comment]
Hello! :)

**Comment by ibharama** [comment]
Hi all

**Comment by GaneshMarkande** [comment]
Hi

**Comment by githubteacher** [comment]
Hello!

**Comment by anjithan** [comment]
Hello

**Comment by ambpac1220** [comment]
Hello

**Comment by shahulirshad** [comment]
Hi
